### PR TITLE
Set nodejs as the target while compilation

### PR DESCRIPTION
**Pull request by ducky427**

### CODE REVIEW

**Comment by nasser** [comment]
The reason we don't compile with nodejs as the target is we never `require` the emitted script. We instead effectively `eval` is into a context: https://github.com/nasser/clojurescript-npm/blob/master/lib/clojurescript.js#L11

The nodejs target adds an annoying shebang to the top of bootstrap.js that I have to manually remove every time. I am not sure what else it does outside of the shebang and setting `*target*`.

Do you think there's a way to set `*target*` directly? It didn't seem to like `(set! *target* "nodejs")`

**Comment by nasser** [comment]
This might do it https://github.com/clojure/clojurescript/commit/00a9b7bde0c8823175560b453a00e7be09ddd250

**Comment by ducky427** [comment]
Regarding the shebang that can be omitted as well. see [this](https://github.com/clojure/clojurescript/wiki/Compiler-Options#hashbang)

**Comment by ducky427** [comment]
let me work this as well. feeding/bathing time for my baby. so will be back at it later in the day.

**Comment by nasser** [comment]
Added the `:hashbang` option and merged. Thanks for the code and the guidance!

**Comment by ducky427** [comment]
thats awesome. brilliant!

**Pull request merged**
